### ISSUE TITLE
After 500 steps.

### ISSUE THREAD

**Issue by arvind1705** [Eyyub/tensorflow-pix2pix#1]
How to use the model ?

**Comment by eyyub** [comment]
What do you mean by using the model?

**Comment by janpf** [comment]
I guess he asks how to import a saved model and using said model to predict new images

**Comment by eyyub** [comment]
Ok I see, thanks.
Well, the model is saved using a `Saver` object, so to load it you can use the `Saver.restore` method. To predict new images you need to use the `sample_generator` method, take a look at `example.py`

**Comment by janpf** [comment]
added a prediction script in my pull request #2
my predict.py can be either used as a form of validation on a testset or as a prediction script

**Comment by arvind1705** [comment]
Got it.
Thanks.
